### ISSUE TITLE
온고지신의 시간

### ISSUE THREAD

**Issue by noveler17** [emiru/emiru-draft#1]
### 웬 온고지신?

네이버 카페에서 시작한 새벽공방 커뮤니티 공간을 새로이 하자는 마음은 모두가 동일하지만, 같은 공간을 대하는 방법과 바라는 점은 분명 모두 다를 것입니다.

온고지신(溫故知新). 옛것을 익히고 그것을 미루어서 새것을 안다는 공자의 말입니다. 기존에 사용하던 카페와 라인에서 어떤 점이 좋았고 어떤 점이 불편했는지 어떠한 경험이 인상적으로 남았는지 의견을 나누어 봅시다. 또한 그 과정에서 우리가 원하는 새로운 공간이 어떠한 모습인지 각자 그려보는 시간을 가집시다.

### 목표

- 기존 시스템(네이버 카페, 라인)에 대한 이해
  - 좋은 점. 앞으로도 있었으면 하는 점.
  - 나쁜 점. 앞으로 배제되거나 바뀌었으면 하는 점. 
  - 시스템 때문에 겪은 재미난 경험
  - 시스템 때문에 겪은 불쾌한 경험
- 새로운 시스템에 대한 그림을 각자 그려 보기
  - 목적
  - 방법

### 주의할 점

- 서로의 판단을 저해할 수 있기 때문에 일단 목적에 대한 부분은 가능한 한 언급하지 말아야 합니다.
  - 요건 다음 이슈로 취합할 예정입니다.
- 시스템에 대한 측면만을 생각합시다. 특정 멤버를 언급하는 것은 좋은 일이어도 가능한 한 삼갑시다.
- 서로 다른 건은 가능한 한 분리하여 코멘트를 작성합시다.

### 기한
아마 이번 주 주말까지.

**Comment by noveler17** [comment]
네이버 카페에서 좋은 점은 역시 '기록'인 듯. 좋은 것이든 나쁜 것이든 어찌 되든 남는다는 게 좋아 보임.

**Comment by kkndplus** [comment]
공방이 이용중인 네이버 카페와 라인의 좋은 점은 '기록' 보다 '접근성' 인듯. 라인은 카톡에 비해 접근성이 떨어지긴 하지만, '네이버'라는 같은 집합(?)을 통해 이용하기 때문에 다른 집합(?)을 쓰기 보단 한 집합(?) 안에 있는 것을 쓰는게 편하지.
대부분 네이버 메일을 많이 사용하기 때문에 카페도 접근이 편한 네이버 카페를 쓰는거고, 우린 여기서 더 나아가 라인을 쓰는거고.

**Comment by fluegelvonciya** [comment]
제 개인적인 생각으로는 네이버카페의 단점으로는 (라인에 비해) 상대적으로 어려운 초기 접근성, 그리고 모두가 즐길 수 있는 카페만의 콘텐츠 부족을 꼽고싶네요.
아무리 카페앱이 있어도 기본적인 커뮤는 라인으로도 충분하고 굳이 카페엔 자주 즐겨볼만한 메리트도 없으니 매일 체크할 동기도 부족하고요.

그러므로 이번 프로젝트는 접근성을 극복하도록
모두가 이용할 수 있는 콘텐츠(작품추천이라던가) 또는
콘텐츠 확장면에서 기록을 편하게(라인에 던지는것처럼 제목과 주소정도같이, 또는 가볍게 쓰는 글)할 수 있는 공간을 만들어 접근의 메리트를 만들었으면 좋겠습니다.

덤으로 우리 ftp서버와의 연동도 있으면 좋겠습니다. 다운로드 링크부터 서버내 자료 목록, 소개페이지같이요.
(예시는 어디까지나 언급됐던 말 또는 설명을 위한것이니 크게 신경 안쓰셔도 됩니당..)

**Comment by noveler17** [comment]
라인을 쓰면서 부족했던 건 공지 기능이 아니었나 생각해. 일반 대화로 남길 수도 없고 그렇다고 포스트로 남겨도 UI 자체가 새 포스트가 있는지 알아보기 힘든 구조였던 것 같아. 그래서 운영하는 사람이 공지를 하거나 의견 수렴이 어렵지 않았나 싶어.

**Comment by fluegelvonciya** [comment]
써놓고보니 저 실수한 거 같기도하고 아리까리한데
새 시스템에대한 목적과 방법에서
목적이 뭘 의미하는거죠?

**Comment by noveler17** [comment]
말 그대로 목적과 방법. 시스템을 바라보는 유저의 목적이 다르다는 얘기야. 당연히 시스템은 하나고 유저는 여럿이니 이대로는 의견 취합은 물론 구현 자체가 안 되겠지. 구현이 되더라도 누구 취향인지 모를 납득할 수 없는 괴물이 되던가.

그래서 일단 지금까지 겪어왔던 기능에 대한 이모저모가 필요한 거야. 지금까지 뭘 해 왔는지 알아야 앞으로도 가져갈 것과 이제는 버려야 하는 것을 이해할 수 있으니까.

그리고 이런 것들에 대해 의견을 취합하는 과정에서 서로 어떤 눈으로 새벽공방을 바라보고 있었는지 이해할 수 있을 거라고 봐. 그 자체가 가치판단이니까. 그러면 앞으로 뭐가 추가되면 좋겠는지가 눈에 보이지 않을까?

설명을 위해서 예를 들까 하다가 각자 생각할 수 있는 바를 저해할까 싶어서 구체적으로 언급하진 않았어. 이해가 안 간다면 다른 방법으로 설명해 볼 테니까 코멘트 줘.

**Comment by noveler17** [comment]
그리고 서로 다른 건은 가능한 한 분리해서 적어 달라니깐!

**Comment by rusi0224** [comment]
개인적으로 카페는 접근성이 좀 떨어진다고 생각되었습니다.
글을 한번 쓰기도 부담스럽고 무언가 공략같은걸 올리지 않으면 안되는듯한 느낌이어서 그런지 '무겁다'는 느낌을 많이 받아 글을 작성하기가 어려웠습니다.

**Comment by noveler17** [comment]
그러고 보니 난 글 쓸 때마다 분류를 어찌 해야 하나 고민이 많았어. 워낙 이것저것 하기 때문인지는 몰라도 카페의 게시판 분류는 항상 그때그때 관심사에 맞게 분류되기 힘든 구성이었던 것 같아.

**Comment by thelaven** [comment]
이게 시스템에 대한 이야기인지는 모르겠지만 까페에서 글을 쓸 때 열심히 쓰다가 오류 라던가 기타 문제로 인해 썼던 글이 전부 날라가는 일이 몄번 있었거든. 열심히 쓰던 입장에서 그렇게 되니까 짜증이 너무 났던 기억이 있어서 만약 새로운 까페를 만든다면 gmail에서 메일 쓰는것처럼 임시로 내가 쓰는 글이 저장 되는 시스템이 있었으면 한다

**Comment by noveler17** [comment]
@thelaven 그건 이미 기능이 있을 텐데, 혹시 설정을 잘못한 게 아닐까?;

**Comment by reavil** [comment]
확실히 카페에 글을 쓰려고 하면 뭔가 내용이 있는 글을 써야할거같아서 안쓰게 되더라고요.
내용없는 글은 카페에 쓰는거보다 라인에 쓰는게 즉각적인 반응도 살펴볼 수 있고, 그 주제로 적당히 웃고 떠들다 (창 올라가면) 넘길 수 있어서 라인을 주로 쓰게되고요.

그리고 카페 접근성이 떨어지죠.
로그인도 불편하고, (명령했을때) 응답속도도 라인에 비해 떨어지고
폰으로 카페에 글 쓰는것도 라인에 쓰는것과는 다르게 (상대적으로) 복잡하고.

정보를 얻을때도 카페에 질문 올리는거보다 라인에 질문하는게 대답이 훨신 빨리 돌아오니까,
라인을 많이 쓴거 같아요.

**Comment by noveler17** [comment]
@reavil @fluegelvonciya 다음부터는 서로 다른 건은 나누어서 써 주길 바랍니다. ;ㅅ;

**Comment by reavil** [comment]
@noveler17 네

**Comment by noveler17** [comment]
이 이슈는 여기에서 종료하고 다음 이슈에서 좀 더 이야기를 나누어 봅시다!
