### ISSUE TITLE
대표 이미지를 만들어 봅시다!

### ISSUE THREAD

**Issue by noveler17** [emiru/emiru-draft#2]
아까 낸 아이디어는 진행 단계에 맞추어 조금씩 완성되어 가는 그림이었는데, 다른 의견이 있어도 좋을 듯합니다.  솔직히 말하자면, 그냥 따라갈 생각이니까, 그림쟁이들이 자율적으로 말씀과 의견을 나누어 주세요.

그리고 혹시나 해서 말씀드리면,
```
Attach files by dragging & dropping, selecting them, or pasting from the clipboard.
```
코멘트 입력하는 창 밑에 있는 요 말들을 해석하면,
```
드래그 & 드롭, 선택하기, 또는 클립보드에서 붙여넣어 파일을 첨부하세요.
```
가 됩니다. 부디 혼란하지 않길 바랍니다. :D

**Comment by rusi0224** [comment]
바로 드래그해서 이미지를 올릴 수 있는 부분 편하네요!

조금씩 완성되는 그림도 괜찮지만 일단은 대표 캐릭터를 하나 만드는게 좋을것 같다고 생각합니다.
현재 그 초록 얼굴 디폴트로 놔두긴 좀 애매하니 임시로 하나 걸어두고 공식 캐릭터 시안도 뽑아보고 하는게 어떨까요?

**Comment by noveler17** [comment]
아무래도 모바일에서는 나오지 않는 메시지여서 모를 것 같았어. 'ㅡ'ㅋ

음, 난 루시 생각에 찬성. 그런 방향도 좋다고 생각해!

**Comment by fluegelvonciya** [comment]
임시 캐릭터가 앞으로 구상될 캐릭의 초안이 된다던가 그런 생성될 대표이미지의 기반이 되는 게 아니라면
임시캐릭 생각하고 그리고 할 거 없이 그냥 그 형네 집 고양이 사진 하나 걸어놓고
바로 캐릭터 구상 시안 들어가도 좋지 않을까요?

**Comment by noveler17** [comment]
응? 그런 거도 좋지. 그나저나 고양이라니!

**Comment by thelaven** [comment]
닥치고 나나코

**Comment by rusi0224** [comment]
요정이미지로 하려고합니다. 찰랑거리는 머리, 엘프귀를가진 너무 튀지않는 부드러운이미지로
갈까 생각중인데 어떤가요?

**Comment by fluegelvonciya** [comment]
@rusi0224 만세

**Comment by fluegelvonciya** [comment]
@rusi0224 라고 쓰긴했지만 그 건은 새로운 이슈로 등록하고
요정 외에도 여론을 모아 다른 소재를 추천받아서 시작하는게 어떨까요?

**Comment by rusi0224** [comment]
@fluegelvonciya 이슈 올렸습니다.

**Comment by noveler17** [comment]
그렇다면 좀 더 심화된 이슈가 생겼으니까 이 이슈는 클로즈!
