### ISSUE TITLE
대표 캐릭터 컨셉 의견 받습니다.

### ISSUE THREAD

**Issue by rusi0224** [emiru/emiru-draft#4]
간판이 되는 캐릭터를 만드는만큼 신중하게 작업하기 위해 의견을 받도록 하겠습니다.

'어떤어떤 스타일에 어떤 이미지였으면 좋겠다'  형식으로 달아주셔도 좋고, 설명하기 복잡하다 싶으시면 참고가 될 만한 캐릭터를 쓰셔도 좋습니다. 자유롭게 적어주시기 바랍니다.

어느정도 의견이 나왔다 싶으면 제가 취합하여 시안을 그려 올리도록 하겠습니다.

**Comment by rusi0224** [comment]
요정 컨셉, 긴머리카락에 엘프 귀, 부드럽고 차분한 인상의 캐릭터

**Comment by fluegelvonciya** [comment]
시스템이 일단 커뮤기능을 보조해 줄 것 같으니 
정장을 입혀주고 하이힐 신겨줬음 좋겠네요.
비서같은 이미지로요!

헉ㅇ허ㅏ헉헉 ^q ^

**Comment by fluegelvonciya** [comment]
시스템이 일단 커뮤기능을 보조해 줄 것 같으니 
정장을 입혀주고 하이힐 신겨줬음 좋겠네요.
비서같은 이미지로요!

헉ㅇ허ㅏ헉헉 ^q ^

**Comment by fluegelvonciya** [comment]
시스템이 일단 커뮤기능을 보조해 줄 것 같으니 
정장을 입혀주고 하이힐 신겨줬음 좋겠네요.
비서같은 이미지로요!

헉ㅇ허ㅏ헉헉 ^q ^

**Comment by noveler17** [comment]
@fluegelvonciya 헐, 그 사이 하나 지웠어!

**Comment by noveler17** [comment]
편안한 인상이었으면 좋겠다!

**Comment by noveler17** [comment]
아, 혹시 수다스런 인상이면 어떨까? 정말 이런저런 이야기를 막 던질 수 있는 분위기 같이.

**Comment by thelaven** [comment]
지적인 이미지, 모노클 안경, 푸른 생머리를 한번 묶은거
시계장인 컨셉, 복장은 약간 펑퍼짐한 장인 복장, 평소에는 온화하지만 일을 할 때는 집중하는 타입,거유 아님(적당하거나 빈유 둘 중 하나)

**Comment by thelaven** [comment]
공방 까페이니 장인이라는 이미지로 설정함

**Comment by misi5** [comment]
개인적인 편견으론 이런캐릭은 위에서말한 요정느낌이거나 미쿠처럼 사이버?한 옷을 입는게 어울린다생각합니다. 물론 그캐릭터가 다른옷을 입을수도있겠지만 스텐다드는 요정 or 사이버틱

**Comment by artdlswl** [comment]
매드 사이언티스트 까지는 아니어도 연구원 어떻습니까. 병을 들고 테스트하는 느낌으로

**Comment by misi5** [comment]
롱부츠 롱장갑!

**Comment by kkndplus** [comment]
![gamedonga_20141229164903599](https://cloud.githubusercontent.com/assets/16032882/11496350/99689418-9854-11e5-84db-aca77f148be2.png)
그림이 좀 아닐수도 있는데. 여튼 엘소드의 시엘 이미지. (집사 스타일)

**Comment by thelaven** [comment]
연구원도 좋군!

**Comment by reavil** [comment]
검은 오버니에 의한 절대영역!

**Comment by fluegelvonciya** [comment]
약간 기우일지도 모르겠지만,
완성될 캐릭터는 너무 선정적이진 않았음 좋겠습니다.
사람에 따라선 그게 또 다른 부담이 될 수 있다고 생각하거든요.
얼마나 이미지가 쓰일진 모르겠지만 그래도 혹시..

(속이 쓰리다..)

**Comment by noveler17** [comment]
@fluegelvonciya 와, 이렇게 설득력이 없게 들릴 줄이야.

**Comment by misi5** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

517jiminsuk@naver.com 님께 보내신 메일 <Re: [emiru-draft] 대표 캐릭터 컨셉 의견 받습니다. (#4)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
