### ISSUE TITLE
커뮤니티 캐릭터 러프 시안

### ISSUE THREAD

**Issue by rusi0224** [emiru/emiru-draft#5]
![416c3a4e-9e08-11e5-8f5d-4c4b1a7a345a](https://cloud.githubusercontent.com/assets/16033518/11660200/5e9129fc-9e0f-11e5-8c5d-83fdb406214e.png)

공방분들의 의견을 크게 보아 어느정도 중복된다 싶은것들은 묶고, 이미지화 시켜보았습니다.

캐릭터 디자인 포인트

- 그리기 편한 느낌
- 복잡하지 않은 디자인
- 밝거나 차분한 분위기

컨셉별로 번호가 적혀있습니다. 
선호하시는 컨셉 번호를 코멘트에 적어주세요.
 
ps. 선호도가 가장 높은 컨셉으로 선정되며 디테일화에 들어갑니다. 
특징을 부여할 아이디어가 있으실 경우 선택하실 컨셉과 함께 적어주시면 검토 후 반영하도록 하겠습니다. 예) 머리에 팬티를 씌워주시면 좋을것 같습니다.

**Comment by noveler17** [comment]
헐, 아무 생각 없이 눌렀는데 엄청 고퀄이라 깜짝 놀랐음!!

**Comment by sg00192** [comment]
6번이 좋습니다 잡혀갈수도 있지만 6번이...

**Comment by noveler17** [comment]
와, 이거 꼭 선택해야 하나요? 정말 하나만 선택해야 하나요? 깨물어서 안 아픈 손가락 없는 느낌인데. ;ㅅ;

**Comment by thelaven** [comment]
이건 5번이다 5번

**Comment by misi5** [comment]
안아픈손까락은없지만 아픔을느끼는차이는있을겁니다 헤헤
전3번 갑니다

**Comment by noveler17** [comment]
1, 2, 4, 5 복수 선택 갑니다. 결정 장애가 왔지만 그래도 마음이 들뜨네요. 작업한 @rusi0224 한테 박수!

**Comment by misi5** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

517jiminsuk@naver.com 님께 보내신 메일 <Re: [emiru-draft] 커뮤니티 캐릭터 러프 시안 (#5)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by misi5** [comment]
머리에 팬티를 씌워주시면 좋을것 같습니다.

**Comment by crus-silt** [comment]
기호 2번. 부디 기호 2번에 깨끗한 한 표를.

**Comment by thelaven** [comment]
갑자기 떠오른 건데 5번 옆에 시계모양 집사 캐릭 있으면 어떨까?
성격은 잔걱정(마스터 걱정) 많고 새가슴에 약간 잘난체 하지만
잔정이 많아서 알게 모르게 주변 사람들 다 챙겨 주는 그런 캐릭터로

**Comment by kkndplus** [comment]
3번을 찍겠네.

**Comment by thelaven** [comment]
커뮤니티의 대표 캐릭터는 차분하고 중심을 잡아줄수 있는 캐릭터가 되어야 한다고 생각 합니다. 이 후 추가로 생길수도(거의 반드시 생길거 같지만) 있는 캐릭터들을 가운데에서 조율해주는 맏언니 같은 캐릭터가 커뮤니티 대표 캐릭터가 되어야 한다고 생각 합니다

**Comment by thelaven** [comment]
그러니 5번

**Comment by fluegelvonciya** [comment]
이 이슈로 정해질 캐릭터는 단순한 캐릭터가 아닌, 프로젝트로 만들어질 시스템의 대표 이미지 입니다.
그러므로 만들어질 시스템의 이미지를 잘 표현해주는 캐릭터가 좋겠네요.
현재까지의 진행상황으로 봐서는 사용중인 시스템의 장단점을 추려내여 *우리의 커뮤니티를 도와주는 프로그램*이 될 것으로 보입니다.

그러므로 사무를 도와주는 일반적인 이미지인 비서 또는 OL의 *1번*.
또는 *3번*의 전자요정 컨셉도 어울린다고 생각합니다.
(헤어는 별로지만)

**Comment by mistyisle** [comment]
1번이 괜찮을 것 같네요.

**Comment by misi5** [comment]
창주형의 반론을 하게되어 죄송하지만 보통 중심을 잡아주는 차분한캐릭은 2 3번째로 나오게되는게 정석이라생각합니다. 보컬로이드를봐도 미쿠처럼 활발한캐릭이나온뒤 루카가나오게되었고 요즘 방영중인 해커돌을 봐도 2호가중심을 잡아줍니다 그런고로 3번!

**Comment by crus-silt** [comment]
요정이란 단어는 저희 공방에서도 의미 있는 단어이고(아니면.. 말고...) 커뮤니티가 멀리 떨어져 있는 공방 사람들을 신비한 힘으로 이어주는 요정 같다는 이미지로서 2번이 괜찮다고 생각합니다! 비슷한 의미로 3번도 괜찮긴하지만 이쪽은 취향에 손을 들어 2번! 모두 외쳐! EE!

**Comment by rusi0224** [comment]
불똥튀기는 코멘트들ㅋㅋㅋㅋ표가 꽤 갈리는것 같아 재밌네요

**Comment by reavil** [comment]
헠ㅋㅋㅋㅋㅋ 으으 하나만 골라야 하나요?
1, 2, 4, 5가 끌리는데... 으으으...
그래도 하나만 고른다면 5번...... (크흐... 으으으.....)
검은 니삭스 부탁드립니다!

1, 5번이 무언가 설명해줄거 같은 느낌의 캐릭터인데, 1번은 뭔가 좀 츤츤끼가 보여서 친절한 설명을 해줄거 같은 5번을! 
4번은 뭔가 모니터 안에서 도와준다는 전자정령의 느낌이(루시형의 컨셉과는 다른듯 하지만), 2번은 일 안하고 옆에서 (뭐하는지) 지켜보다 만화책 보고 할거 같은 느낌이...

**Comment by thelaven** [comment]
상당히... 박빙이네

**Comment by artdlswl** [comment]
1번과 5번을 적절히 섞으면 좋을거라 생각합니다.
그럼 연금술사 혹은 약사의 느낌을 낼 수도?
