### ISSUE TITLE
무엇을 가져 가고, 무엇을 버리고 갈까요?

### ISSUE THREAD

**Issue by noveler17** [emiru/emiru-draft#6]
지금까지 #3 을 통해서 기존까지 사용해 온 네이버 카페와 라인에 대해서 살펴 보았습니다. 각자의 경험을 한 데 묶어 보니 언뜻 서로 비슷하게 보이기도 하지만, 생각하지도 못한 부분에서 깊은 의견을 보이는 경우도 있어서 특히 더 새로웠던 것 같습니다.

그런 의미에서 이번에 해 보고자 하는 것은

## 기존 시스템의 요소요소에 대해서 선택해 나가자!

가 되겠습니다.

#3 을 한 번씩 더 확인해 보고 앞으로도 반드시 챙겨야겠다 싶은 것과 이건 정말 반드시 버려야겠다 하는 게 있다면 각자 언급해 주세요. 순서는 전혀 상관 없으며 서로의 의견에 논의하는 것도 좋습니다.

혹시 확인하러 가지 않을 사람들이 있을까 하여 여기에 관련 내용을 다시 적겠습니다.

#### 공통적으로 나타나는 특성
- 장점
  -  대중적인 네이버와 관련되어 동작하기에 추가 가입이 불필요
- 단점
  -  모두가 즐길 수 있는 컨텐츠 부족

##### 네이버 카페
- 장점
  - 카페 내 모든 컨텐츠를 대상으로 검색 가능
- 단점
  - 새 글을 작성하기 어려움
    - 어느 정도 형식을 갖춘 글을 써야 할 것 같은 부담감
    - 글을 써도 사람들의 반응이 늦음
  - 추가 관리 소요
    - 게시글 분류가 공방 구성원들의 관심사 변화를 따라가지 못함
  - 떨어지는 접근성
    - 카페 시스템 자체의 응답이 느림
    - 로그인 등이 불편하게 느껴짐
    - 메일, 쪽지 확인 중 접근하기 쉽게 디자인되어 있지만 그러한 행동 자체가 활성화되지 않음
  
##### 라인
- 장점
  - 모바일 환경에 기인하는 편리한 사용성
    - 멤버들 모두가 모바일 기기를 이용함
    - 모든 커뮤니케이션이 실시간으로 이루어짐
      - 다른 사람의 말에 빠른 피드백 가능
  - 가벼운 분위기
    - 가벼운 대화 위주의 구성
    - 타 사이트로의 링크만 올리는 것도 허용
- 단점
  - 대화를 기록할 방법이 없으며, 마찬가지로 검색할 수도 없음
    - 계속해서 글이 밀려 올라가기 때문에 뒤쳐지지 않게 모든 메시지를 읽어야 함
  - 추가 관리 소요
    - 공지를 위한 기능이 없음
      - 포스트 기능이 있으나 의견 조율이나 진행 상황을 표현은 어려움

## 주의할 점은 좋은 점을 강화, 나쁜 점을 극복할 방법이 떠오른다면 공유하자!

막상 떠오르는 게 없다 하더라도 위에서 언급한 것처럼 분류하는 것만으로도 충분히 가치롭지 않을까 합니다. 그런 의미에서 일단 다함께 의견을 나누어 봅시다.

**Comment by fluegelvonciya** [comment]
일단 꼭 가져갔음 하는 요소로는
라인의 **가벼운 글 작성 가능**을 꼽고싶네요.
종종 올라오는 유머나 정보 링크글만 모아둬도 카페의 단점인 *모두가 즐길 수 있는 콘텐츠 부재*를 상당량 해결할 수 있을 것으로 봅니다.

**Comment by fluegelvonciya** [comment]
그리고 라인의 단점으로 언급되었으며
#3에 명시되진 않았지만 카페의 장점이라고 생각하는 **공지게시판**의 존재도 뽑아보고싶네요.
그런 기능도 꼭 가져갔음 좋겠습니다.
진행중, 완료된이벤트로 나누는 필터 기능 포함해서요

**Comment by fluegelvonciya** [comment]
마지막으로 **의견 조율상황을 알기 어렵다**라는 요소는
써보니 깃헙처럼 주제별로 주르륵 나오는게 괜찮네요.
다만 여기도 의견나눔리플과 확정리플을 구분해주는(예시로 리플의 배경색이라던가)
필터 기능을 넣었으면 좋겠습니다.

**Comment by rusi0224** [comment]
재현이의 의견에 대부분 공감가는편이라 따로 더 적을건 없지만, 추가적으로 가져갔으면 하는 부분은 모바일에 좀더 최적화된 구성이면 좋겠다는 것, 태그별로 글들이 알아서 적절한 카테고리에 배치되는 기능도 있었으면 좋겠다는 생각입니다.

**Comment by reavil** [comment]
모바일에서도 지원이 된다면 라인처럼 한 번의 클릭으로 빠르게 접근할 수 있었으면 좋겠습니다.
여기서 빠르게란, 매 번 실행할때 마다 로그인을 하지 않고 카톡이나 라인처럼 한 번 로그인 하면 그 이후에는 로그인을 할 필요가 없었으면 좋겠습니다. 인터넷의 자동로그인기능처럼 일정 기간이 지나면 캐시가 삭제되어 다시 로그인 하지 않도록요.

**Comment by reavil** [comment]
또한 앱 실행속도 역시 너무 느리지 않으며도록 해야 사람들이 자주 이용할 거라 생각합니다. 카페를 자주 이용하지 않았던 것 중 하나가 네이버 로그인 시간이 좀 걸려 더욱 기피했던것 같습니다. 특히 로그인하다 한참 뒤에 로그인 실패했다고 뜨는 창을 봤을 때는.. ㅂㄷㅂㄷ...
