### ISSUE TITLE
전체적인 프로젝트의 진행 계획을 알고싶습니다!

### ISSUE THREAD

**Issue by fluegelvonciya** [emiru/emiru-draft#7]
처음엔 온고지신으로 아이디어를 모았고,
6번 이슈로 아이디어간 우선순위의 취합을 해보았습니다.

앞으로도 어떻게 진행할 것인지 개략적인 플랜을 알려주세요.

**Comment by noveler17** [comment]
1. 기존에 사용하던 커뮤니티 파악
2. 분석된 요소 중 가져가야 하는 것과 버려야 하는 것 구분
3. 추가로 가미(또는 강조)하고 싶은 요소 도출
4. 나열된 요소 중 우선순위 선정
5. 우선순위 기반으로 MVP(Minimun Value Product) 구현
6. 진행이 잘 된다면 이 다음부터는 차순위 요소들을 개발

**Comment by noveler17** [comment]
아무래도 지금은 2번과 3번 사이라고 할 수 있을 듯. 3번 하다가 말았으니까.

**Comment by fluegelvonciya** [comment]
@noveler17 이대로 이거 이슈 닫아버리긴 좀 그렇고,
저 플랜은 리드미에 써넣고 닫으면 되겠죠?

**Comment by noveler17** [comment]
@fluegelvonciya 그러면 좋을 듯! 부탁함!
